# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    - camel_case_types
    - non_constant_identifier_names

analyzer:
  exclude: [build/**, test/**/*.g.dart, lib/**/*.g.dart]
  errors:
    uri_has_not_been_generated: ignore
