name: dartvectormap
description: Dart Angular implementation of Jsvectormap
version: 0.0.1
author: Mikhail Stepanov <mstepanov214@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  equatable: ^1.2.3

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
